services:
  socket_proxy:
    image: tecnativa/docker-socket-proxy:latest
    container_name: socket_proxy
    hostname: socket_proxy
    restart: unless-stopped
    networks:
      - socket-traefik
      - socket-logstash
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      ALLOW_RESTARTS: 0
      AUTH: 0
      BUILD: 0
      COMMIT: 0
      CONFIGS: 0
      # Needed for traefik
      CONTAINERS: 1
      DISTRIBUTION: 0
      EVENTS: 1
      EXEC: 0
      IMAGES: 0
      # Needed for logstash
      INFO: 1
      LOG_LEVEL: info
      NETWORKS: 0
      NODES: 0
      PING: 1
      PLUGINS: 0
      # When POST is disabled, only GET and HEAD operations are allowed,
      # meaning any section of the API is read-only 
      POST: 0
      SECRETS: 0
      SERVICES: 0
      SESSION: 0
      SWARM: 0
      SYSTEM: 0
      TASKS: 0
      VERSION: 1
      VOLUMES: 0

networks:
  socket-traefik:
    name: socket-traefik
    driver: bridge
    internal: "true"
  socket-logstash:
    name: socket-logstash
    driver: bridge
    internal: "true"
