services:
  wekandb:
    image: mongo:4.4.8
    container_name: wekan-db
    restart: unless-stopped
    command: mongod --oplogSize 128
    volumes:
      - wekan-db:/data/db
      - wekan-db-dump:/dump

  wekan:
    image: wekanteam/wekan:latest
    container_name: wekan-app
    restart: unless-stopped
    #ports:
    #  - 8080:8080
    environment:
      - MONGO_URL
      - ROOT_URL
      - MAIL_URL
      - MAIL_FROM
      - WITH_API
      - RICHER_CARD_COMMENT_EDITOR
      - SCROLLINERTIA
      - SCROLLAMOUNT
      - CARD_OPENED_WEBHOOK_ENABLED
      - BIGEVENTS_PATTERN
      - BROWSER_POLICY_ENABLED
      - PASSWORD_LOGIN_ENABLED
    depends_on:
      - wekandb
    networks:
      - default
      - tr-wekan
    labels:
      # Expose the container
      traefik.enable: "true"
      # Specify the network to be used with traefik
      traefik.docker.network: tr-wekan
      # Specify the service url
      traefik.http.routers.wekan.rule: Host(`wekan.example.int`)
      # Specify the internal service port
      traefik.http.services.wekan.loadbalancer.server.port: 8080
      # Only allow entry on specified ports 
      traefik.http.routers.wekan.entrypoints: int, int-https
      # Enable tls
      traefik.http.routers.wekan.tls: true
      # Set the service name
      traefik.http.routers.wekan.service: wekan

volumes:
  wekan-db:
    driver: local
  wekan-db-dump:
    driver: local

networks:
  tr-wekan:
    external: true
    name: tr-wekan
